### ISSUE TITLE
[Bug] Can't flash json files from configurator

### ISSUE THREAD

**Issue by thequailman** [qmk/qmk_firmware#11711]
## Describe the Bug

After exporting a keymap.json file, I can't flash it using QMK:

```
$ qmk flash $(pwd)/preonic.json
<class 'TypeError'>
☒ parse_configurator_json() got an unexpected keyword argument 'parallel'
Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.9/site-packages/milc/milc.py", line 461, in __call__
    return self.__call__()
  File "/home/mike/.local/lib/python3.9/site-packages/milc/milc.py", line 466, in __call__
    return self._entrypoint(self)
  File "/home/mike/qmk_firmware/lib/python/qmk/decorators.py", line 42, in wrapper
    return func(*args, **kwargs)
  File "/home/mike/qmk_firmware/lib/python/qmk/decorators.py", line 85, in wrapper
    return func(*args, **kwargs)
  File "/home/mike/qmk_firmware/lib/python/qmk/cli/flash.py", line 79, in flash
    user_keymap = parse_configurator_json(cli.args.filename, parallel=cli.config.flash.parallel)
TypeError: parse_configurator_json() got an unexpected keyword argument 'parallel'
```
## System Information

 - Keyboard:  
   - Revision (if applicable):  preonic/rev3
 - Operating system: Debian Bullseye
 - AVR GCC version: 5.4.0

 - ARM GCC version: 8.3.1

 - QMK Firmware version: 0.11.53

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by Erovia** [comment]
Thanks for reporting this bug.
#11765 should fix it, please reopen the issue and ping me if not.

**Comment by thequailman** [comment]
Thank you!!!!
