### ISSUE TITLE
[Bug] Incorrect "Python too old" error

### ISSUE THREAD

**Issue by NiklasBr** [qmk/qmk_firmware#13184]
Python version 3.8 is not detected, qmk believes it is <3.7.

## Describe the Bug

At the end of running `qmk setup -H ~/workspace/qmk_firmware` the following output happens:

```
Ψ Successfully cloned https://github.com/qmk/qmk_firmware to /home/niklas/workspace/qmk_firmware!
Ψ Added https://github.com/qmk/qmk_firmware as remote upstream.
Would you like to set /home/niklas/workspace/qmk_firmware as your QMK home? [y/n] y
Ψ Wrote configuration to /home/niklas/.config/qmk/qmk.ini
Warning: The bin/qmk script is being deprecated. Please install the QMK CLI: python3 -m pip install qmk
Error: Your Python is too old! Please upgrade to Python 3.7 or later.
niklas@Fractal:~/workspace$ python --version
Python 3.8.0
```

## System Information

 - Keyboard:  
   - Revision (if applicable):  
 - Operating system:
 - AVR GCC version: 

 - ARM GCC version: 

 - QMK Firmware version: `0.13.5`

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

## Additional Context

This is Ubuntu 18.04 running in WSL2 in Windows 10.

After running `alias python3=python3.8` the following happens: 
```
niklas@Fractal:~/workspace$ qmk setup -H ~/workspace/qmk_firmware
☒ Could not find qmk_firmware!
Would you like to clone qmk/qmk_firmware to /home/niklas/workspace/qmk_firmware? [y/n] y
Cloning into '/home/niklas/workspace/qmk_firmware'...
Submodule 'lib/chibios' (https://github.com/qmk/ChibiOS) registered for path 'lib/chibios'
Submodule 'lib/chibios-contrib' (https://github.com/qmk/ChibiOS-Contrib) registered for path 'lib/chibios-contrib'
Submodule 'lib/googletest' (https://github.com/qmk/googletest) registered for path 'lib/googletest'
Submodule 'lib/lufa' (https://github.com/qmk/lufa) registered for path 'lib/lufa'
Submodule 'lib/printf' (https://github.com/qmk/printf) registered for path 'lib/printf'
Submodule 'lib/ugfx' (https://github.com/qmk/uGFX) registered for path 'lib/ugfx'
Submodule 'lib/vusb' (https://github.com/qmk/v-usb) registered for path 'lib/vusb'
Cloning into '/home/niklas/workspace/qmk_firmware/lib/chibios'...
Cloning into '/home/niklas/workspace/qmk_firmware/lib/chibios-contrib'...
Cloning into '/home/niklas/workspace/qmk_firmware/lib/googletest'...
Cloning into '/home/niklas/workspace/qmk_firmware/lib/lufa'...
Cloning into '/home/niklas/workspace/qmk_firmware/lib/printf'...
Cloning into '/home/niklas/workspace/qmk_firmware/lib/ugfx'...
Cloning into '/home/niklas/workspace/qmk_firmware/lib/vusb'...
Submodule path 'lib/chibios': checked out 'ffe54d63cb10a355add318f8e922e39f1c3d4bfd'
Submodule path 'lib/chibios-contrib': checked out '61baa6b036138c155f7cfc5646d833d9423f3243'
Submodule path 'lib/googletest': checked out 'ec44c6c1675c25b9827aacd08c02433cccde7780'
Submodule path 'lib/lufa': checked out 'ce10f7642b0459e409839b23cc91498945119b4d'
Submodule path 'lib/printf': checked out 'd3b984684bb8a8bdc48cc7a1abecb93ce59bbe3e'
Submodule path 'lib/ugfx': checked out '40b48f470addad6a4fb1177de1a69a181158739b'
Submodule path 'lib/vusb': checked out 'bdb53e4c043d089279d9891b68bea77614cb97ee'
Ψ Successfully cloned https://github.com/qmk/qmk_firmware to /home/niklas/workspace/qmk_firmware!
Ψ Added https://github.com/qmk/qmk_firmware as remote upstream.
Would you like to set /home/niklas/workspace/qmk_firmware as your QMK home? [y/n] y
Ψ Wrote configuration to /home/niklas/.config/qmk/qmk.ini
Error: %s: %s ('ImportError', ImportError('Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll'))
Traceback (most recent call last):
  File "/home/niklas/.local/lib/python3.8/site-packages/qmk_cli/script_qmk.py", line 76, in main
    import qmk.cli  # noqa
  File "/home/niklas/workspace/qmk_firmware/lib/python/qmk/cli/__init__.py", line 158, in <module>
    from . import console  # noqa
  File "/home/niklas/workspace/qmk_firmware/lib/python/qmk/cli/console.py", line 9, in <module>
    import hid
  File "/home/niklas/.local/lib/python3.8/site-packages/hid/__init__.py", line 30, in <module>
    raise ImportError(error)
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll
```

**Comment by azzamsa** [comment]
Why do you have this error: `ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll`

Do you have hidapi or `libhidapi-dev` installed?

**Comment by zvecr** [comment]
This issue has been automatically closed because it has not had any recent activity.
If this issue is still valid, re-open the issue and let us know.
