### ISSUE TITLE
Bad CPU type in executable: 'avr-gcc'

### ISSUE THREAD

**Issue by kasselvania** [qmk/qmk_firmware#14929]
Hello,
I'm trying to get QMK setup on my 2018 MacBook Pro i9 and the setup protocol happens to break every time. I set up everything until I get this retruned:

> Ψ Found qmk_firmware at /Users/peterkassel/qmk_firmware.
> Ψ QMK Doctor is checking your environment.
> Ψ CLI version: 1.0.0
> Ψ QMK home: /Users/peterkassel/qmk_firmware
> Ψ Detected macOS 11.6.
> Ψ Git branch: master
> Ψ CLI installed in virtualenv.
> ☒ Can't find arm-none-eabi-gcc in your path.
> <class 'OSError'>
> ☒ [Errno 86] Bad CPU type in executable: 'avr-gcc'
> Traceback (most recent call last):
>   File "/Users/peterkassel/homebrew/Cellar/qmk/1.0.0_1/libexec/lib/python3.9/site-packages/milc/milc.py", line 514, in __call__
>     return self.__call__()
>   File "/Users/peterkassel/homebrew/Cellar/qmk/1.0.0_1/libexec/lib/python3.9/site-packages/milc/milc.py", line 519, in __call__
>     return self._subcommand(self)
>   File "/Users/peterkassel/qmk_firmware/lib/python/qmk/cli/doctor/main.py", line 92, in doctor
>     bin_ok = check_binaries()
>   File "/Users/peterkassel/qmk_firmware/lib/python/qmk/cli/doctor/check.py", line 104, in check_binaries
>     if not is_executable(binary):
>   File "/Users/peterkassel/qmk_firmware/lib/python/qmk/cli/doctor/check.py", line 144, in is_executable
>     check = cli.run([command, version_arg], combined_output=True, stdin=DEVNULL, timeout=5)
>   File "/Users/peterkassel/homebrew/Cellar/qmk/1.0.0_1/libexec/lib/python3.9/site-packages/milc/milc.py", line 161, in run
>     return subprocess.run(command, **kwargs)
>   File "/Users/peterkassel/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/Users/peterkassel/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/Users/peterkassel/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> OSError: [Errno 86] Bad CPU type in executable: 'avr-gcc'
> 

I've tried almost everything I can think of, but not sure why this would be returned. Anybody have a tip?

**Comment by tzarc** [comment]
Closing due to inactivity.
