### ISSUE TITLE
KeyError in submodule handling

### ISSUE THREAD

**Issue by harmathy** [qmk/qmk_firmware#18371]
If the git option `log.showSignature` is set to *true*, then `qmk setup` will fail with:

```
<class 'KeyError'>
☒ 'gpg: Signature made Wed Jul 27 17:46:15 2022 JST'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/milc/milc.py", line 528, in __call__
    return self.__call__()
  File "/usr/lib/python3.10/site-packages/milc/milc.py", line 533, in __call__
    return self._subcommand(self)
  File "/home/max/qmk_firmware/lib/python/qmk/cli/doctor/main.py", line 140, in doctor
    sub_ok = check_submodules()
  File "/home/max/qmk_firmware/lib/python/qmk/cli/doctor/check.py", line 120, in check_submodules
    for submodule in submodules.status().values():
  File "/home/max/qmk_firmware/lib/python/qmk/submodules.py", line 50, in status
    submodules[submodule]['shorthash'] = r[1] if len(r) > 1 else ''
KeyError: 'gpg: Signature made Wed Jul 27 17:46:15 2022 JST'
```

The option can be set via

```
git config --global log.showSignature true
```

**Comment by harmathy** [comment]
The problem is the call of `git log` here https://github.com/qmk/qmk_firmware/blob/f483520ff9b66cebacf880c4b079b2c490a7e80a/lib/python/qmk/submodules.py#L43

One solution would be adding parameter `--no-show-signature`.
