### ISSUE TITLE
[Feature Request] Hillside 48 working keymap.c

### ISSUE THREAD

**Issue by manny-reyes** [qmk/qmk_firmware#22059]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

The Hillside 48 keyboard default keymap in QMK currently seems only to be set up for the QMK Configurator. Would it be possible to have a working keymap.c set up for that one? I am having trouble building my own keymap without a working template.

**Comment by manny-reyes** [comment]
OK, that helped produce a keymap.c, thanks! The compile errors aren't nearly as bad now, but it still doesn't seem to be working properly. Here is what I am seeing:
`QMK Firmware 0.12.29
Making hillside/48/0_1 with keymap default

☒ not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/milc/milc.py", line 467, in __call__
    return self.__call__()
  File "/usr/local/lib/python3.9/site-packages/milc/milc.py", line 472, in __call__
    return self._entrypoint(self)
  File "/Users/manny/qmk_firmware/lib/python/qmk/decorators.py", line 42, in wrapper
    return func(*args, **kwargs)
  File "/Users/manny/qmk_firmware/lib/python/qmk/decorators.py", line 85, in wrapper
    return func(*args, **kwargs)
  File "/Users/manny/qmk_firmware/lib/python/qmk/cli/generate/rules_mk.py", line 58, in generate_rules_mk
    kb_info_json = dotty(info_json(cli.config.generate_rules_mk.keyboard))
  File "/Users/manny/qmk_firmware/lib/python/qmk/info.py", line 46, in info_json
    layouts, aliases = _find_all_layouts(info_data, keyboard)
  File "/Users/manny/qmk_firmware/lib/python/qmk/info.py", line 387, in _find_all_layouts
    layouts, aliases = _search_keyboard_h(Path(keyboard))
  File "/Users/manny/qmk_firmware/lib/python/qmk/info.py", line 374, in _search_keyboard_h
    new_layouts, new_aliases = find_layouts(keyboard_h_path)
  File "/Users/manny/qmk_firmware/lib/python/qmk/c_parse.py", line 56, in find_layouts
    macro_name, layout, matrix = _parse_layout_macro(line.strip())
  File "/Users/manny/qmk_firmware/lib/python/qmk/c_parse.py", line 152, in _parse_layout_macro
    layout, matrix = layout.split(')', 1)
ValueError: not enough values to unpack (expected 2, got 1)
build_keyboard.mk:101: <class: No such file or directory
build_keyboard.mk:101: 'ValueError'>: No such file or directory
build_keyboard.mk:368: tmk_core/protocol/avr.mk: No such file or directory
make[1]: *** No rule to make target `tmk_core/protocol/avr.mk'.  Stop.
make: *** [hillside/48/0_1:default] Error 1
Make finished with errors
`

**Comment by manny-reyes** [comment]
Thanks for your patience. Here's the output:
```
Ψ QMK Doctor is checking your environment.
Ψ Detected macOS.
Ψ QMK home: /Users/manny/qmk_firmware
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 8.3.1
Ψ Found avr-gcc version 8.4.0
Ψ Found avrdude version 6.3
Ψ Found dfu-util version 0.10
Ψ Found dfu-programmer version 0.7.2
Ψ Submodules are up to date.
Ψ QMK is ready to go
```

**Comment by manny-reyes** [comment]
That did the trick! Typing on the board (with my own firmware) right now! Thanks for your help.
