### ISSUE TITLE
HOW to solve this problem

### ISSUE THREAD

**Issue by Aaron970103** [qmk/qmk_firmware#23039]
### Issue Description

☒ 'rgb_matrix'
Traceback (most recent call last):
  File "C:/QMK_MSYS/mingw64/lib/python3.11/site-packages/milc/milc.py", line 539, in __call__
    return self.__call__()
           ^^^^^^^^^^^^^^^
  File "C:/QMK_MSYS/mingw64/lib/python3.11/site-packages/milc/milc.py", line 544, in __call__
    return self._subcommand(self)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:/KEYBOARD/qmk_firmware/lib/python/qmk/cli/generate/rules_mk.py", line 65, in generate_rules_mk
    kb_info_json = dotty(info_json(cli.args.keyboard))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:/KEYBOARD/qmk_firmware/lib/python/qmk/info.py", line 216, in info_json
    info_data = _extract_led_config(info_data, str(keyboard))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:/KEYBOARD/qmk_firmware/lib/python/qmk/info.py", line 728, in _extract_led_config
    if info_data[feature].get("layout", None) and not info_data[feature].get("led_count", None):
       ~~~~~~~~~^^^^^^^^^
KeyError: 'rgb_matrix'

 *                                                                                                     [ERRORS]

builddefs/build_keyboard.mk:226: *** Platform not defined。
![星愿浏览器截图20240209000544](https://github.com/qmk/qmk_firmware/assets/159469112/36c49e4a-4e26-4903-bfdc-aabafb586d5a)

**Comment by fauxpark** [comment]
Update your repo.
