### ISSUE TITLE
[Bug] qmk setup on arch linux fails: conflicting subparser console

### ISSUE THREAD

**Issue by uykusuz** [qmk/qmk_firmware#24228]
### Describe the Bug

Hi there,

I followed the [getting started guide](https://docs.qmk.fm/newbs_getting_started) to install qmk on Arch Linux. Then I run the `qmk setup`  and the problem below appears.

I tried both, installed the community package qmk and qmk-git and now also tried the python way using pip install. Every way produces this error?

Can anyone help me out here?

```
Traceback (most recent call last):
  File "/home/bobbel/qmk_firmware/venv/bin/qmk", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/bobbel/qmk_firmware/venv/lib/python3.12/site-packages/qmk_cli/script_qmk.py", line 76, in main
    import qmk.cli  # noqa
    ^^^^^^^^^^^^^^
  File "/home/bobbel/qmk_firmware/lib/python/qmk/cli/__init__.py", line 213, in <module>
    __import__(subcommand)
  File "/home/bobbel/qmk_firmware/lib/python/qmk/cli/console.py", line 261, in <module>
    @cli.subcommand('Acquire debugging information from usb hid devices.', hidden=False if cli.config.user.developer else True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bobbel/qmk_firmware/venv/lib/python3.12/site-packages/milc/milc.py", line 708, in subcommand_function
    return self.add_subcommand(handler, description, hidden=hidden, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bobbel/qmk_firmware/venv/lib/python3.12/site-packages/milc/milc.py", line 689, in add_subcommand
    self.subcommands[name] = SubparserWrapper(self, name, self._subparsers.add_parser(name, **kwargs))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 1219, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument {config,clone,console,env,setup,c2json,chibios-confmigrate,clean,compile}: conflicting subparser: console
```

### Keyboard Used

didn't get that far

### Operating System

Arch linux

### qmk doctor Output

```text
this one outputs the same as qmk setup
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by uykusuz** [comment]
thanks a lot for the fast reponse!
