### ISSUE TITLE
[Bug] qmk setup fails with `ValueError`

### ISSUE THREAD

**Issue by kdheepak** [qmk/qmk_firmware#8541]
The output of `avr-gcc --version` is:

```
avr-gcc (Homebrew AVR GCC 8.4.0) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

This causes the following error:

```
$ qmk setup kdheepak .

Ψ Found qmk_firmware at ..
Ψ QMK Doctor is checking your environment.
Ψ Detected macOS.
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 8.3.1
AVR
<class 'ValueError'>
☒ not enough values to unpack (expected 3, got 1)
Traceback (most recent call last):
  File "/Users/USER/.local/Cellar/qmk/0.0.29/libexec/lib/python3.7/site-packages/milc.py", line 592, in __call__
    return self.__call__()
  File "/Users/USER/.local/Cellar/qmk/0.0.29/libexec/lib/python3.7/site-packages/milc.py", line 597, in __call__
    return self._entrypoint(self)
  File "/Users/USER/gitrepos/qmk_firmware/lib/python/qmk/cli/doctor.py", line 242, in doctor
    if not check_avr_gcc_version():
  File "/Users/USER/gitrepos/qmk_firmware/lib/python/qmk/cli/doctor.py", line 53, in check_avr_gcc_version
    major, minor, rest = version_number.split('.', 2)
ValueError: not enough values to unpack (expected 3, got 1)
☒ Your build environment is not setup completely.
*** Would you like to run util/qmk_install? [y/n] y
Updating Homebrew...
```

In https://github.com/qmk/qmk_firmware/blob/b936048b0bf2b5508104e243089e785debc431d0/lib/python/qmk/cli/doctor.py#L51 using 

        version_number = first_line.split()[-1]

instead works for me.

**Comment by StreakInTheSky** [comment]
Found this bug as well, and did the same fix. Not sure if it's strictly a mac/homebrew issue. Which could explain why this was missed.

**Comment by fauxpark** [comment]
This might be because the version string changed, so the item at index 2 is now the string "AVR" instead of the version. Perhaps we should use the `-dumpversion` flag instead:

```
fauxpark@marissa:~$ avr-gcc -dumpversion
8.4.0
fauxpark@marissa:~$ arm-none-eabi-gcc -dumpversion
8.3.1
```

**Comment by StreakInTheSky** [comment]
Tried changing `is_executable` to run with -dumpversion instead, but the other items in `ESSENTIAL_BINARIES` return status codes greater than 1. So would have to either change the only flag for those two items, or just change how it checks the string for avr-gcc, which would be easier.
